;;
;; Copyright (c) 2020-2026, Intel Corporation
;;
;; SPDX-License-Identifier: BSD-3-Clause
;;
%define SUBMIT_JOB_ZUC128_EEA3 submit_job_zuc_eea3_gfni_sse
%define FLUSH_JOB_ZUC128_EEA3 flush_job_zuc_eea3_gfni_sse
%define SUBMIT_JOB_ZUC_NEA6 submit_job_zuc_nea6_gfni_sse
%define FLUSH_JOB_ZUC_NEA6 flush_job_zuc_nea6_gfni_sse
%define SUBMIT_JOB_ZUC128_EIA3 submit_job_zuc_eia3_gfni_sse
%define FLUSH_JOB_ZUC128_EIA3 flush_job_zuc_eia3_gfni_sse
%define ZUC_EIA3_4_BUFFER zuc_eia3_4_buffer_job_gfni_sse
%define SUBMIT_JOB_ZUC_NIA6 submit_job_zuc_nia6_gfni_sse
%define FLUSH_JOB_ZUC_NIA6 flush_job_zuc_nia6_gfni_sse
%define ZUC_EIA3_4_BUFFER zuc_eia3_4_buffer_job_gfni_sse
%define ZUC_NIA6_4_BUFFER zuc_nia6_4_buffer_job_gfni_sse
%define ZUC128_INIT_4 asm_ZucInitialization_4_gfni_sse
%define ZUCNEA6_INIT_4 asm_ZucNEA6Initialization_4_gfni_sse
%define ZUC_CIPHER_4      asm_ZucCipher_4_gfni_sse
%define ZUC_NCA6_4_BUFFER zuc_nca6_4_buffer_job_gfni_sse
%define SUBMIT_JOB_ZUC_NCA6 submit_job_zuc_nca6_gfni_sse
%define FLUSH_JOB_ZUC_NCA6 flush_job_zuc_nca6_gfni_sse
%include "sse_t1/mb_mgr_zuc_submit_flush_sse.asm"
