/*******************************************************************************
  Copyright (c) 2026, Intel Corporation

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:

      * Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.
      * Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.
      * Neither the name of Intel Corporation nor the names of its contributors
        may be used to endorse or promote products derived from this software
        without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*******************************************************************************/

/**
 * FIPS 204 Section 6 "Internal Functions" states: "Other than for testing
 * purposes, the interfaces for key generation and signature generation
 * specified in this section should not be made available to applications,
 * as any random values required for key generation and signature generation
 * shall be generated by the cryptographic module. [...] the interfaces
 * specified in this section will be used when testing of ML-DSA
 * implementations is performed through the CAVP."
 *
 * This header declares the subset of the ML-DSA API that exists solely to
 * satisfy that CAVP/ACVP testing requirement: the FIPS 204 internal
 * Sign_internal/Verify_internal interface (Section 6). It is deliberately
 * not part of the installed, public intel-ipsec-mb.h header, so applications
 * linking against the library never see these prototypes.
 *
 * These functions are exported from the library for external linkage (so
 * that test/certification harnesses such as kat-app/acvp-app can link
 * against them by including this header directly from the source tree), but
 * they are intended only for CAVP/ACVP conformance testing and similar
 * internal validation - not for use by customer/application code. Note that
 * caller-supplied-randomness signing (via IMB_ML_DSA_SIGN_PARAMS::rnd_32)
 * remains part of the always-public API in intel-ipsec-mb.h and is declared
 * there instead.
 */

#ifndef IMB_ML_DSA_INTERNAL_API_H
#define IMB_ML_DSA_INTERNAL_API_H

#include <stdint.h>
#include <stddef.h>

#include <intel-ipsec-mb.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Sign a message using the FIPS 204 internal interface (ML-DSA.Sign_internal).
 *        No context string, no message encoding. Intended for composite schemes that
 *        perform their own external-interface encoding, and for ACVP/CAVP
 *        conformance testing of the internal interface.
 *        Requires a private key to have been bound to \a self via
 *        imb_ml_dsa_keypair() or imb_ml_dsa_set_privkey().
 *
 * @param [in]  self           ML-DSA context with a bound private key
 * @param [out] sig            Signature buffer (variant SIG_BYTES)
 * @param [out] sig_len        Produced signature length in bytes
 * @param [in]  msg            Message buffer
 * @param [in]  msg_len        Message length in bytes
 * @param [in]  rnd_32_or_null 32-byte randomizer, or NULL to have a fresh
 *                             randomizer generated internally (hedged
 *                             signing). Pass 32 zero bytes for FIPS 204
 *                             deterministic signing (e.g. ACVP conformance
 *                             testing).
 * @return Operation status
 * @retval 0 success
 * @retval IMB_ERR_NULL_CTX invalid \a self pointer
 * @retval IMB_ERR_NULL_DST invalid \a sig or \a sig_len pointer
 * @retval IMB_ERR_NULL_SRC invalid \a msg pointer
 * @retval IMB_ERR_PQC_NO_KEY no private key bound to \a self
 * @retval IMB_ERR_PQC_SIGNOP signing operation failed
 *
 * @warning Per FIPS 204 Section 6, the internal Sign_internal interface
 * should not be made available to applications outside of CAVP/ACVP
 * conformance testing or composite-scheme use. This function is not
 * declared in the public intel-ipsec-mb.h header; it is only intended to be
 * used by internal test/certification applications that include this
 * header directly from the source tree.
 */
IMB_DLL_EXPORT int
imb_ml_dsa_sign_internal(IMB_ML_DSA *self, uint8_t *sig, size_t *sig_len, const uint8_t *msg,
                         size_t msg_len, const uint8_t *rnd_32_or_null);

/**
 * @brief Verify a signature over a message using the FIPS 204 internal interface
 *        (ML-DSA.Verify_internal). No context string, no message encoding.
 *        Requires a public key to have been bound to \a self via
 *        imb_ml_dsa_keypair(),
 *        imb_ml_dsa_set_privkey() (private keys carry the public component too) or
 *        imb_ml_dsa_set_pubkey().
 *
 * @param [in] self     ML-DSA context with a bound public key
 * @param [in] msg      Message buffer
 * @param [in] msg_len  Message length in bytes
 * @param [in] sig      Signature buffer
 * @param [in] sig_len  Signature length in bytes
 * @return Operation status
 * @retval 0 the signature is valid
 * @retval IMB_ERR_NULL_CTX invalid \a self pointer
 * @retval IMB_ERR_NULL_SRC invalid \a sig or \a msg pointer
 * @retval IMB_ERR_PQC_NO_KEY no public key bound to \a self
 * @retval IMB_ERR_PQC_SIGNOP the signature is invalid, or verification
 *         could not be performed
 *
 * @warning Per FIPS 204 Section 6, the internal Verify_internal interface
 * should not be made available to applications outside of CAVP/ACVP
 * conformance testing or composite-scheme use. This function is not
 * declared in the public intel-ipsec-mb.h header; it is only intended to be
 * used by internal test/certification applications that include this
 * header directly from the source tree.
 */
IMB_DLL_EXPORT int
imb_ml_dsa_verify_internal(IMB_ML_DSA *self, const uint8_t *msg, size_t msg_len, const uint8_t *sig,
                           size_t sig_len);

#ifdef __cplusplus
}
#endif

#endif /* IMB_ML_DSA_INTERNAL_API_H */
