/*******************************************************************************
  Copyright (c) 2026, Intel Corporation

  SPDX-License-Identifier: BSD-3-Clause
*******************************************************************************/

/**
 * FIPS 204 Section 6 "Internal Functions" states: "Other than for testing
 * purposes, the interfaces for key generation and signature generation
 * specified in this section should not be made available to applications,
 * as any random values required for key generation and signature generation
 * shall be generated by the cryptographic module. [...] the interfaces
 * specified in this section will be used when testing of ML-DSA
 * implementations is performed through the CAVP."
 *
 * This header declares the subset of the ML-DSA API that exists solely to
 * satisfy that CAVP/ACVP testing requirement: the FIPS 204 internal
 * Sign_internal/Verify_internal interface (Section 6). It is deliberately
 * not part of the installed, public intel-ipsec-mb.h header, so applications
 * linking against the library never see these prototypes.
 *
 * @important These functions are exported from the library for external
 * linkage purely so that test/certification harnesses (kat-app, acvp-app)
 * can link against them by including this header directly from the source
 * tree. They exist ONLY to support ACVP/CAVP conformance testing of the
 * FIPS 204 internal interface and MUST NOT be called by general application
 * code, nor treated as part of the library's public API. Application
 * code must use the public API declared in intel-ipsec-mb.h instead.
 */

#ifndef IMB_ML_DSA_INTERNAL_API_H
#define IMB_ML_DSA_INTERNAL_API_H

#include <stdint.h>
#include <stddef.h>

#include <intel-ipsec-mb.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Sign a message using the FIPS 204 internal interface (ML-DSA.Sign_internal).
 *        No context string, no message encoding. Exported solely for ACVP/CAVP
 *        conformance testing of the internal interface - not intended for use
 *        by other applications (see @warning below).
 *        Requires a private key to have been bound to \a self via
 *        imb_ml_dsa_keypair() or imb_ml_dsa_set_privkey().
 *
 * @param [in]      self           ML-DSA context with a bound private key
 * @param [out]     sig            Signature buffer (variant SIG_BYTES)
 * @param [in,out]  sig_len        On entry, the capacity of \a sig in bytes.
 *                                 On success, overwritten with the produced
 *                                 signature length in bytes (variant SIG_BYTES).
 * @param [in]      msg            Message buffer
 * @param [in]      msg_len        Message length in bytes
 * @param [in]      rnd_32_or_null 32-byte randomizer, or NULL to have a fresh
 *                                 randomizer generated internally (hedged
 *                                 signing). Pass 32 zero bytes for FIPS 204
 *                                 deterministic signing (e.g. ACVP conformance
 *                                 testing).
 * @param [in]      rnd_len        Size of \a rnd_32_or_null in bytes. Must be
 *                                 IMB_ML_DSA_SIGN_RND_BYTES when
 *                                 \a rnd_32_or_null is not NULL, otherwise must
 *                                 be 0.
 * @return Operation status
 * @retval 0 success
 * @retval IMB_ERR_NULL_CTX invalid \a self pointer
 * @retval IMB_ERR_NULL_DST invalid \a sig or \a sig_len pointer
 * @retval IMB_ERR_NULL_SRC invalid \a msg pointer
 * @retval IMB_ERR_PQC_NO_KEY no private key bound to \a self
 * @retval IMB_ERR_PQC_BUFFER_SIZE \a *sig_len on entry is smaller than
 *         the variant's SIG_BYTES, or \a rnd_len does not match the
 *         randomizer size fixed by FIPS 204 (or is not zero for a NULL
 *         \a rnd_32_or_null)
 * @retval IMB_ERR_PQC_SIGNOP the signing operation failed
 *
 * @warning Per FIPS 204 Section 6, the internal Sign_internal interface is
 * exported ONLY to support ACVP/CAVP conformance testing and MUST NOT be
 * used by other applications. This function is not declared in the public
 * intel-ipsec-mb.h header; it is only intended to be used by internal
 * test/certification applications that include this header directly from
 * the source tree.
 */
IMB_DLL_EXPORT int
imb_ml_dsa_sign_internal(IMB_ML_DSA *self, void *sig, size_t *sig_len, const void *msg,
                         size_t msg_len, const void *rnd_32_or_null, size_t rnd_len);

/**
 * @brief Verify a signature over a message using the FIPS 204 internal interface
 *        (ML-DSA.Verify_internal). No context string, no message encoding.
 *        Exported solely for ACVP/CAVP conformance testing of the internal
 *        interface - not intended for use by other applications (see
 *        @warning below).
 *        Requires a public key to have been bound to \a self via
 *        imb_ml_dsa_keypair(),
 *        imb_ml_dsa_set_privkey() (private keys carry the public component too) or
 *        imb_ml_dsa_set_pubkey().
 *
 * @param [in] self     ML-DSA context with a bound public key
 * @param [in] msg      Message buffer
 * @param [in] msg_len  Message length in bytes
 * @param [in] sig      Signature buffer
 * @param [in] sig_len  Signature length in bytes
 * @return Operation status
 * @retval 0 the signature is valid
 * @retval IMB_ERR_NULL_CTX invalid \a self pointer
 * @retval IMB_ERR_NULL_SRC invalid \a sig or \a msg pointer
 * @retval IMB_ERR_PQC_NO_KEY no public key bound to \a self
 * @retval IMB_ERR_PQC_VERIFY_FAILED the signature is cryptographically
 *         invalid (or malformed)
 * @retval IMB_ERR_PQC_SIGNOP verification could not be performed (an
 *         operational failure unrelated to the signature's validity)
 *
 * @warning Per FIPS 204 Section 6, the internal Verify_internal interface is
 * exported ONLY to support ACVP/CAVP conformance testing and MUST NOT be
 * used by other applications. This function is not declared in the public
 * intel-ipsec-mb.h header; it is only intended to be used by internal
 * test/certification applications that include this header directly from
 * the source tree.
 */
IMB_DLL_EXPORT int
imb_ml_dsa_verify_internal(IMB_ML_DSA *self, const void *msg, size_t msg_len, const void *sig,
                           size_t sig_len);

#ifdef __cplusplus
}
#endif

#endif /* IMB_ML_DSA_INTERNAL_API_H */
