name: FreeBSD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  # CMake release build with Clang
  release-cmake-clang:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Clang Release Build
        uses: vmactions/freebsd-vm@d1e65811565151536c0c894fff74f06351ed26e6 # v1.4.5
        with:
          usesh: true
          mem: 8192
          prepare: pkg install -y curl nasm gmake cmake
          run: |
            echo ">>> CMAKE CONFIGURE"
            cmake -B ./build -DCMAKE_BUILD_TYPE=Release
            echo ">>> CMAKE BUILD"
            cd ./build
            cmake --build . --config Release -j4 -v
            ctest -j 5 -C Release
            echo ">>> CMAKE INSTALL"
            cmake --install .

  # CMake release build with GCC
  release-cmake-gcc:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Release build with GCC
        uses: vmactions/freebsd-vm@d1e65811565151536c0c894fff74f06351ed26e6 # v1.4.5
        with:
          usesh: true
          mem: 8192
          prepare: pkg install -y curl nasm gmake cmake gcc
          run: |
            echo ">>> CMAKE CONFIGURE"
            cmake -B ./build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc
            echo ">>> CMAKE BUILD"
            cd ./build
            cmake --build . --config Release -j4 -v
            ctest -j 5 -C Release
