name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  # CMake release build with shared library (msbuild)
  release-cmake-msvc-msbuild:
    env:
      BUILD_TYPE: Release
    runs-on: windows-latest

    steps:
    - name: Setup NASM
      uses: ilammy/setup-nasm@72793074d3c8cdda771dba85f6deafe00623038b # v1.5.2

    - name: Checkout repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

    - name: Setup environment
      run: |
        New-Item -ItemType Directory -Path "$pwd\build"
        New-Item -ItemType Directory -Path "$pwd\build\bin"
        "BUILD_DIR=$pwd\build" >> $env:GITHUB_ENV
        "BINARY_DIR=$pwd\build\bin" >> $env:GITHUB_ENV
        $env:PATH += "$pwd\build\bin;"

    - name: Configure CMake
      run: cmake -A x64 -DIMB_BIN_DIR=${{env.BINARY_DIR}} -B ${{env.BUILD_DIR}}

    - name: Build
      run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest -j 5 -C ${{env.BUILD_TYPE}} --test-dir ${{env.BUILD_DIR}}

  # CMake debug build with shared library (msbuild)
  debug-cmake-msvc-msbuild:
    env:
      BUILD_TYPE: Debug
    runs-on: windows-latest

    steps:
    - name: Setup NASM
      uses: ilammy/setup-nasm@72793074d3c8cdda771dba85f6deafe00623038b # v1.5.2

    - name: Checkout repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

    - name: Setup environment
      run: |
        New-Item -ItemType Directory -Path "$pwd\build"
        New-Item -ItemType Directory -Path "$pwd\build\bin"
        "BUILD_DIR=$pwd\build" >> $env:GITHUB_ENV
        "BINARY_DIR=$pwd\build\bin" >> $env:GITHUB_ENV
        $env:PATH += "$pwd\build\bin;"

    - name: Configure CMake
      run: cmake -A x64 -DIMB_BIN_DIR=${{env.BINARY_DIR}} -B ${{env.BUILD_DIR}}

    - name: Build
      run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest -j 5 -C ${{env.BUILD_TYPE}} --test-dir ${{env.BUILD_DIR}}
